name: Build Typst document
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_typst:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Typst de
        uses: lvignoli/typst-action@main
        with:
          source_file: CV.typ
          options: |
            CV-de.pdf
            --font-path
            fontawesome
            --input
            lang=de
      - name: Typst de svg
        uses: quiode/typst-action@main
        with:
          source_file: CV.typ
          options: |
            CV-de.svg
            --font-path
            fontawesome
            --input
            lang=de
      - name: Typst en
        uses: quiode/typst-action@main
        with:
          source_file: CV.typ
          options: |
            CV-en.pdf
            --font-path
            fontawesome
            --input
            lang=en
      - name: Typst en svg
        uses: quiode/typst-action@main
        with:
          source_file: CV.typ
          options: |
            CV-en.svg
            --font-path
            fontawesome
            --input
            lang=en
      - name: Create a Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: false
          draft: false
          title: 'Latest CV'
          files: |
            LICENSE
            CV-en.pdf
            CV-de.pdf
            CV-en.svg
            CV-de.svg
